### PR TITLE
Break to mobile for medium and below

### PR DESCRIPTION
**Pull request by tuchfarber**
Sizing consistent with other services.

### CODE REVIEW

**Comment by bill-filler** [comment]
@tuchfarber if you are viewing a page and the TOC is open in large mode and then resize the window, the TOC takes over the whole screen and the page contents are hidden. It should probably be the other way around. If both open and go to mobile mode, the TOC should be hidden and the page remain visible

**Comment by bill-filler** [comment]
Also probably not related to this PR specifically but to mobile in general:
If the page contents have a wide image/doc when switching to mobile mode the header is not sized correctly
screenshot from 2018-09-14 09-45-59

**Comment by bill-filler** [comment]
Also check the breakpoint for the Journal title in the header. It should either be hidden when the header goes to mobile or stay visible in mobile. Currently it's visible in mobile header then disappears when the size is reduced further.

**Comment by tuchfarber** [comment]
@bill-filler 
1) Typically if a menu is open and you move to mobile, the menu stays open. You can see this in our LMS if you click the dropdown in the top right, then shrink. I realize this use case is a little different because the navigation panel will commonly be left open, but I think the % of people affected is low enough that consistency makes more sense. Happy to debate though. 

2) That's an issue with Wagtails Rich-text Image field. When you use that instead of the normal image field it sets a height and width on the element which causes it to flow outside the boundaries. Best option would be for those to be removed. Otherwise our options include hiding the overflow (chops off the rest of the image, no good), setting a max-width (image fits, but since it's height is set inline, it's proportions will be wrong). Easiest fix in my opinion is to strip them out when we are editing the `<embed>`s in the API call.

3) Will fix. That's the only thing that changes on medium (which made sense before) so I missed it.

**Comment by bill-filler** [comment]
@tuchfarber 
1) I think there are two big differences in Journals compared to LMS which make me think our current behavior is not desirable. First, the journals nav panel while technically a menu is a more integral part of the app in our case. Guessing it will typically be left open where as a menu in LMS is really a temporary thing you open to perform an action then it closes. Secondly, in LMS impl even though the menu is left open when going to mobile you can still see the courseware content beneath it, so it's not like the content disappears (as in our case)  it's just lower on the screen. Granted resizing the window won't be a typical operation, if it's not too difficult I think it makes sense to always have the page content visible when switching.

2) Ok, I'll file a ticket to remove the width/height in embed

**Comment by tuchfarber** [comment]
@bill-filler Alright, you've convinced me. Changes made.

**Comment by bill-filler** [comment]
@tuchfarber all good except one case
- open journal full width (large mode)
- open TOC
- manually resize window so that TOC hides
- click Contents menu
- click a page link from the TOC

Expected results:
page is loaded and displayed and TOC is hidden

Actual results:
TOC stays visible and page is not displayed

**Comment by bill-filler** [comment]
@tuchfarber good to merge

**Pull request merged**
