### PR TITLE
XBlock Video Component

### PR DESCRIPTION
**Pull request by BessieSteinberg**

### CODE REVIEW

**Comment by bill-filler** [comment]
Couple of comments and not sure how to fix exactly:

The initial size seems to tall and possibly too wide:
- the height of the video container is too big by default. For me it's adding a bunch of whitespace underneath the video (see attachment)
- seems wrong to have `padding-bottom: 75%` in `XBlockVideoViewer.scss` and also seems wrong to have `height: 0`
- changing `width` in XBlockVideoViewer.scss seems to have no effect at all, which I would think it would.

Ideally I think we'd want the border to fit the size of the video, but because we don't know the video size it might be better to hardcode the width/height of the border and have the iframe fit in that area.

Would be good to have the iframe scrollbars turned off if they are not needed, possbily this can be controlled by iframe attribute `scrolling`

**Comment by bill-filler** [comment]
Another thought. If you press the fullscreen button of the bottom toolbar of the video it fits resizes to fit our container perfectly. We should look into seeing if there is an attribute we can pass to the video url to have it launch fullscreen by default then we'd have no scrollbars or other weird sizing issues.

screenshot from 2018-08-13 16-47-19

**Comment by tuchfarber** [comment]
Couple of notes regarding your comments (since I attempted to fix all these in the backend version originally):
 - The page we are iframing in has takes up something like 110% of the viewable space. What that means is that no matter how big you make the iframe, there will always be a scrollbar. And we can't disable the scrollbar because you can't set CSS on content inside an iframe (it's protected)
- We also can't make the viewer fullscreen by default because it requires an action to happen and we can't run that action inside of an iframe (again, protected)

If we want to fix either of these issues, we'll need to put in work to change the view of these xblocks. The obvious long term solution is to move to a our separate react video player. FedX has talked about this once or twice during meetings. So we can either fix the old, build the new, or let it look the way it does.

**Comment by tuchfarber** [comment]
Still reviewing the sizing stuff though.

**Comment by tuchfarber** [comment]
Played around with sizing a little bit and this was the best I could get it: https://github.com/edx/journals-frontend/commit/b5709f2fb93c1fb3d2d1486059db4748e1f81338 . It set's a max-width for the video, uses responsive stuff that we used in the PDF viewer, and handles different screen sizes.

**Comment by BessieSteinberg** [comment]
This works and is responsive to different screen sizes if your screen size isn't decreased.  Whatever screen size you start with, the video component will appropriately scale to that size.  If you start with a narrow screen size and make your screen wider the video will scale accordingly.  Oddly, once the video has gotten wider it won't scale down. For example, you could start your screen at 500px wide and the video would fit nicely into that, then make your screen 600px wide and the video scales to that, but if you try to make your screen narrower then 600px wide again the video will stay scaled up.  The iframe window will scale properly but the video stays wide and you will get these scroll bars on the bottom.  It's very odd. I'm not sure if there is anything we can do about this though. I think it maybe something to do with the way we are rendering video in lms.
Also thanks to Matt for all the styling help!

**Comment by tuchfarber** [comment]
Yeah, I noticed that as well when I was working on it. Definitely a bug, but I thought the tradeoff might be worth it until we have a video player component. Should have mentioned it in my original comment.

**Pull request merged**
